
knife4j:
  production: true

spring:
  datasource:
    url: jdbc:mysql://rm-wz9sgq38841f27k8v.mysql.rds.aliyuncs.com:3306/yrt?zeroDateTimeBehavior=convertToNull
    password: lphOgXisMJw4LEHN1
    username: yrt_sys
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 100
      
      max-wait: 60000
      
      time-between-eviction-runs-millis: 60000
      
      min-evictable-idle-time-millis: 300000
      
      max-evictable-idle-time-millis: 900000
      
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      
      filters: stat,wall,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSwlMillis=5000
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: 
        url-pattern: /admin/monitor/druid/*
      filter:
        stat:
          enabled: true
          db-type: mysql
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          enabled: true
          db-type: mysql
          config:
            multi-statement-allow: true
            truncate-allow: false
            alterTable-allow: false
            dropTable-allow: false
checkhis:
  flag: true